version: '3'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - ./db/data/postgres/:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
